version: '3.7'

services:
  kurutveckling-mongodb:
    image: mongo:4.4.2

  kursutveckling-api:
    image: $LOCAL_IMAGE_ID
    environment:
      SERVICE_PUBLISH: '/api/kursutveckling'
      SERVER_PORT: 3000
      MONGODB_URI: mongodb://mongodb/kursutveckling
      KURSUTVECKLINGS_API_KEYS_0: '?name=test&apiKey=1234&scope=read'
      LOGGING_ACCESS_LOG: 'true'
    depends_on:
      - kurutveckling-mongodb

  kursutveckling-integration:
    build: ./test/integration
    depends_on:
      - kursutveckling-api
