version: '3.7'

services:
  kursutveckling-api:
    image: $LOCAL_IMAGE_ID

    volumes:
      - ./test:/application/test

    tty: true

    command: ['sh', '-c', 'npm install --development && npm test']
